version: "3"
services:
  web:
    image: rlawncks125/vue-graphql
    build:
      context: ./front-vue
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    environment:
      - PORTS=8888
    volumes:
      - /usr/src/app/node_modules
      - ./front-vue:/usr/src/app
      - ./front-vue/node_modules/@types:/usr/src/app/node_modules/@types
    container_name: vue-graphQL

  DB:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD='password'
    ports:
      - 3306:3306
    volumes:
      - ./mariadb/mysql_data:/var/lib/mysql
    container_name: graphql-mariadb

  back:
    image: rlawncks125/nest-graphql
    build:
      context: ./backed
      dockerfile: Dockerfile
    ports:
      - 3033:3033
    environment:
      - PORTS=3033
      - DB_HOST=DB
      - DB_PORT=3306
      - DB_ROOT=root
      - DB_PASSWORD='password'
      - DB_DATABASE='database'
      - JWT_KEY='jwt-key'
      - ENV=Local
    volumes:
      - ./backed:/usr/src/app
    container_name: nest-graphQL
